# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dashboard_form(object):
    def setupUi(self, dashboard_form):
        dashboard_form.setObjectName("dashboard_form")
        dashboard_form.resize(800, 600)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(dashboard_form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 641, 604))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.playlist_list = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.playlist_list.setObjectName("playlist_list")
        self.verticalLayout.addWidget(self.playlist_list)
        self.manage_playlist = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.manage_playlist.setObjectName("manage_playlist")
        self.verticalLayout.addWidget(self.manage_playlist)
        self.manage_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.manage_button.setObjectName("manage_button")
        self.verticalLayout.addWidget(self.manage_button)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.music_play_name = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.music_play_name.setObjectName("music_play_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.music_play_name)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.music_play_lyrics = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.music_play_lyrics.setObjectName("music_play_lyrics")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.music_play_lyrics)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.playlist_title_line_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.playlist_title_line_2.setObjectName("playlist_title_line_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.playlist_title_line_2)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.playlist_duration_line_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.playlist_duration_line_2.setObjectName("playlist_duration_line_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.playlist_duration_line_2)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.playlist_star_line_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.playlist_star_line_2.setObjectName("playlist_star_line_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.playlist_star_line_2)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.public_button_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.public_button_2.setText("")
        self.public_button_2.setObjectName("public_button_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.public_button_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.id_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.id_line.setObjectName("id_line")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.id_line)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.error_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.error_label_2.setText("")
        self.error_label_2.setObjectName("error_label_2")
        self.verticalLayout_5.addWidget(self.error_label_2)
        self.creat_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.creat_button_2.setObjectName("creat_button_2")
        self.verticalLayout_5.addWidget(self.creat_button_2)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(dashboard_form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(640, 0, 172, 213))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.search_button.setObjectName("search_button")
        self.verticalLayout_3.addWidget(self.search_button)
        self.firstPage_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.firstPage_button.setObjectName("firstPage_button")
        self.verticalLayout_3.addWidget(self.firstPage_button)
        self.profile_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.profile_button.setObjectName("profile_button")
        self.verticalLayout_3.addWidget(self.profile_button)
        self.follow_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.follow_button.setObjectName("follow_button")
        self.verticalLayout_3.addWidget(self.follow_button)
        self.rate_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rate_button.setObjectName("rate_button")
        self.verticalLayout_3.addWidget(self.rate_button)
        self.like_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.like_button.setObjectName("like_button")
        self.verticalLayout_3.addWidget(self.like_button)
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout_3.addWidget(self.exit_button)

        self.retranslateUi(dashboard_form)
        QtCore.QMetaObject.connectSlotsByName(dashboard_form)

    def retranslateUi(self, dashboard_form):
        _translate = QtCore.QCoreApplication.translate
        dashboard_form.setWindowTitle(_translate("dashboard_form", "Form"))
        self.label_4.setText(_translate("dashboard_form", "Playlists:"))
        self.manage_button.setText(_translate("dashboard_form", "Manage"))
        self.label.setText(_translate("dashboard_form", "Music played name:"))
        self.music_play_name.setText(_translate("dashboard_form", "No music is playing"))
        self.label_3.setText(_translate("dashboard_form", "Music lyrics: "))
        self.label_9.setText(_translate("dashboard_form", "Create new playlist: "))
        self.label_10.setText(_translate("dashboard_form", "Title:"))
        self.label_11.setText(_translate("dashboard_form", "Duration:"))
        self.label_12.setText(_translate("dashboard_form", "Stars:"))
        self.label_13.setText(_translate("dashboard_form", "Public:"))
        self.label_2.setText(_translate("dashboard_form", "Id: "))
        self.creat_button_2.setText(_translate("dashboard_form", "Create"))
        self.search_button.setText(_translate("dashboard_form", "Search menu"))
        self.firstPage_button.setText(_translate("dashboard_form", "First page"))
        self.profile_button.setText(_translate("dashboard_form", "Profile"))
        self.follow_button.setText(_translate("dashboard_form", "Follow"))
        self.rate_button.setText(_translate("dashboard_form", "Rate and Follow Playlist"))
        self.like_button.setText(_translate("dashboard_form", "Like Music"))
        self.exit_button.setText(_translate("dashboard_form", "Exit"))

