# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager_profile.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_manager_profile_form(object):
    def setupUi(self, manager_profile_form):
        manager_profile_form.setObjectName("manager_profile_form")
        manager_profile_form.resize(800, 600)
        self.formLayoutWidget_2 = QtWidgets.QWidget(manager_profile_form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(320, 0, 481, 591))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.liked_mu_view_2 = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.liked_mu_view_2.setObjectName("liked_mu_view_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.liked_mu_view_2)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.tags_view_2 = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.tags_view_2.setObjectName("tags_view_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tags_view_2)
        self.add_tag_button_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.add_tag_button_2.setObjectName("add_tag_button_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.add_tag_button_2)
        self.tags_combo_2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.tags_combo_2.setObjectName("tags_combo_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tags_combo_2)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.listen_mu_view_2 = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.listen_mu_view_2.setObjectName("listen_mu_view_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.listen_mu_view_2)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.post_music_view_2 = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.post_music_view_2.setObjectName("post_music_view_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.post_music_view_2)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.playlist_view_2 = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.playlist_view_2.setObjectName("playlist_view_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.playlist_view_2)
        self.manage_playlist_2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.manage_playlist_2.setObjectName("manage_playlist_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.manage_playlist_2)
        self.manage_playlist_button_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.manage_playlist_button_2.setObjectName("manage_playlist_button_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.manage_playlist_button_2)
        self.error_label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.error_label_2.setText("")
        self.error_label_2.setObjectName("error_label_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.error_label_2)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.manage_user_button = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.manage_user_button.setObjectName("manage_user_button")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.manage_user_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(manager_profile_form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 311, 591))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.photo_choose = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.photo_choose.setObjectName("photo_choose")
        self.verticalLayout_2.addWidget(self.photo_choose)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.username_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.username_label.setText("")
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.email_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.email_label.setText("")
        self.email_label.setObjectName("email_label")
        self.horizontalLayout_2.addWidget(self.email_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.change_pass_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.change_pass_button.setObjectName("change_pass_button")
        self.verticalLayout.addWidget(self.change_pass_button)
        self.delete_ac_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.delete_ac_button.setObjectName("delete_ac_button")
        self.verticalLayout.addWidget(self.delete_ac_button)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.follow_num = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.follow_num.setText("")
        self.follow_num.setObjectName("follow_num")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.follow_num)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.following_num = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.following_num.setText("")
        self.following_num.setObjectName("following_num")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.following_num)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.dashboard_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.dashboard_button_2.setObjectName("dashboard_button_2")
        self.verticalLayout_4.addWidget(self.dashboard_button_2)

        self.retranslateUi(manager_profile_form)
        QtCore.QMetaObject.connectSlotsByName(manager_profile_form)

    def retranslateUi(self, manager_profile_form):
        _translate = QtCore.QCoreApplication.translate
        manager_profile_form.setWindowTitle(_translate("manager_profile_form", "Form"))
        self.label_14.setText(_translate("manager_profile_form", "Liked music: "))
        self.label_15.setText(_translate("manager_profile_form", "Tags: "))
        self.add_tag_button_2.setText(_translate("manager_profile_form", "Add Tag"))
        self.label_16.setText(_translate("manager_profile_form", "Listened music:"))
        self.label_17.setText(_translate("manager_profile_form", "Last posted musics: "))
        self.label_18.setText(_translate("manager_profile_form", "Playlists:"))
        self.manage_playlist_button_2.setText(_translate("manager_profile_form", "Manage"))
        self.manage_user_button.setText(_translate("manager_profile_form", "Manage users"))
        self.photo_choose.setText(_translate("manager_profile_form", "Change"))
        self.label_2.setText(_translate("manager_profile_form", "Username: "))
        self.label_3.setText(_translate("manager_profile_form", "Email: "))
        self.change_pass_button.setText(_translate("manager_profile_form", "Change password"))
        self.delete_ac_button.setText(_translate("manager_profile_form", "Delete account"))
        self.label_4.setText(_translate("manager_profile_form", "Followers: "))
        self.label_5.setText(_translate("manager_profile_form", "Following: "))
        self.dashboard_button_2.setText(_translate("manager_profile_form", "Dashboard"))

