# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_user.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_manage_user_form(object):
    def setupUi(self, manage_user_form):
        manage_user_form.setObjectName("manage_user_form")
        manage_user_form.resize(800, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(manage_user_form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.playlist_widget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.playlist_widget.setObjectName("playlist_widget")
        self.verticalLayout.addWidget(self.playlist_widget)
        self.playlist_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.playlist_combo.setObjectName("playlist_combo")
        self.verticalLayout.addWidget(self.playlist_combo)
        self.playlist_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playlist_button.setObjectName("playlist_button")
        self.verticalLayout.addWidget(self.playlist_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.music_widget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.music_widget.setObjectName("music_widget")
        self.verticalLayout_2.addWidget(self.music_widget)
        self.music_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.music_combo.setObjectName("music_combo")
        self.verticalLayout_2.addWidget(self.music_combo)
        self.music_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.music_button.setObjectName("music_button")
        self.verticalLayout_2.addWidget(self.music_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.user_widget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.user_widget.setObjectName("user_widget")
        self.verticalLayout_3.addWidget(self.user_widget)
        self.user_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.user_combo.setObjectName("user_combo")
        self.verticalLayout_3.addWidget(self.user_combo)
        self.user_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.user_button.setObjectName("user_button")
        self.verticalLayout_3.addWidget(self.user_button)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(manage_user_form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(515, 0, 261, 571))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.request_widget = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        self.request_widget.setObjectName("request_widget")
        self.verticalLayout_4.addWidget(self.request_widget)
        self.request_combo = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.request_combo.setObjectName("request_combo")
        self.verticalLayout_4.addWidget(self.request_combo)
        self.accept_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.accept_button.setObjectName("accept_button")
        self.verticalLayout_4.addWidget(self.accept_button)
        self.back_button = QtWidgets.QPushButton(manage_user_form)
        self.back_button.setGeometry(QtCore.QRect(240, 570, 321, 32))
        self.back_button.setObjectName("back_button")

        self.retranslateUi(manage_user_form)
        QtCore.QMetaObject.connectSlotsByName(manage_user_form)

    def retranslateUi(self, manage_user_form):
        _translate = QtCore.QCoreApplication.translate
        manage_user_form.setWindowTitle(_translate("manage_user_form", "Form"))
        self.label.setText(_translate("manage_user_form", "All playlists: "))
        self.playlist_button.setText(_translate("manage_user_form", "Delete"))
        self.label_2.setText(_translate("manage_user_form", "All musics:"))
        self.music_button.setText(_translate("manage_user_form", "Delete"))
        self.label_3.setText(_translate("manage_user_form", "All users: "))
        self.user_button.setText(_translate("manage_user_form", "Delete"))
        self.label_4.setText(_translate("manage_user_form", "Requested creating new song:"))
        self.accept_button.setText(_translate("manage_user_form", "Accept"))
        self.back_button.setText(_translate("manage_user_form", "Back"))

