# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_playlist.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_manage_playlist_form(object):
    def setupUi(self, manage_playlist_form):
        manage_playlist_form.setObjectName("manage_playlist_form")
        manage_playlist_form.resize(800, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(manage_playlist_form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 401, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.new_playlist_name_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.new_playlist_name_line.setObjectName("new_playlist_name_line")
        self.horizontalLayout.addWidget(self.new_playlist_name_line)
        self.rename_ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rename_ok_button.setObjectName("rename_ok_button")
        self.horizontalLayout.addWidget(self.rename_ok_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(manage_playlist_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 240, 351, 278))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.song_title_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.song_title_line.setObjectName("song_title_line")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.song_title_line)
        self.song_writer_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.song_writer_line.setObjectName("song_writer_line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.song_writer_line)
        self.duration_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.duration_line.setObjectName("duration_line")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.duration_line)
        self.lyrics_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lyrics_line.setObjectName("lyrics_line")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lyrics_line)
        self.photo_choose = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.photo_choose.setObjectName("photo_choose")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.photo_choose)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.id_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.id_line.setObjectName("id_line")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.id_line)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.add_new_song_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_new_song_button.setObjectName("add_new_song_button")
        self.verticalLayout.addWidget(self.add_new_song_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(manage_playlist_form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(600, 490, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.remove_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout_3.addWidget(self.remove_button)
        self.back_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.back_button.setObjectName("back_button")
        self.verticalLayout_3.addWidget(self.back_button)

        self.retranslateUi(manage_playlist_form)
        QtCore.QMetaObject.connectSlotsByName(manage_playlist_form)

    def retranslateUi(self, manage_playlist_form):
        _translate = QtCore.QCoreApplication.translate
        manage_playlist_form.setWindowTitle(_translate("manage_playlist_form", "Form"))
        self.label.setText(_translate("manage_playlist_form", "Raname the playlist: "))
        self.rename_ok_button.setText(_translate("manage_playlist_form", "Ok"))
        self.label_7.setText(_translate("manage_playlist_form", "Add new music:"))
        self.label_8.setText(_translate("manage_playlist_form", "Title:"))
        self.label_9.setText(_translate("manage_playlist_form", "Song writer:"))
        self.label_10.setText(_translate("manage_playlist_form", "Duration:"))
        self.label_12.setText(_translate("manage_playlist_form", "Lyrics:"))
        self.label_13.setText(_translate("manage_playlist_form", "Photo:"))
        self.photo_choose.setText(_translate("manage_playlist_form", "Choose"))
        self.label_2.setText(_translate("manage_playlist_form", "Id:"))
        self.add_new_song_button.setText(_translate("manage_playlist_form", "Request"))
        self.remove_button.setText(_translate("manage_playlist_form", "Remove playlist"))
        self.back_button.setText(_translate("manage_playlist_form", "Back"))

