# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_register_form(object):
    def setupUi(self, register_form):
        register_form.setObjectName("register_form")
        register_form.resize(800, 600)
        register_form.setStyleSheet("")
        self.image_view = QtWidgets.QGraphicsView(register_form)
        self.image_view.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.image_view.setObjectName("image_view")
        self.formLayoutWidget = QtWidgets.QWidget(register_form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 110, 564, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.username_line.setObjectName("username_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_line)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.email_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.email_line.setObjectName("email_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.email_line)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.password_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setObjectName("password_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_line)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pq_combo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.pq_combo.setObjectName("pq_combo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pq_combo)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pa_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pa_line.setObjectName("pa_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pa_line)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.composer_check = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.composer_check.setObjectName("composer_check")
        self.horizontalLayout.addWidget(self.composer_check)
        self.ordinary_check = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.ordinary_check.setObjectName("ordinary_check")
        self.horizontalLayout.addWidget(self.ordinary_check)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.photo_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.photo_button.setObjectName("photo_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.photo_button)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.verticalLayoutWidget = QtWidgets.QWidget(register_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 370, 381, 93))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_2.addWidget(self.error_label)
        self.reg_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reg_button.setObjectName("reg_button")
        self.verticalLayout_2.addWidget(self.reg_button)
        self.back_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back_button.setObjectName("back_button")
        self.verticalLayout_2.addWidget(self.back_button)

        self.retranslateUi(register_form)
        QtCore.QMetaObject.connectSlotsByName(register_form)

    def retranslateUi(self, register_form):
        _translate = QtCore.QCoreApplication.translate
        register_form.setWindowTitle(_translate("register_form", "Form"))
        self.label.setText(_translate("register_form", "Username"))
        self.label_2.setText(_translate("register_form", "E-Mail"))
        self.label_3.setText(_translate("register_form", "Password"))
        self.label_4.setText(_translate("register_form", "Personal Question"))
        self.label_5.setText(_translate("register_form", "Answer"))
        self.label_6.setText(_translate("register_form", "Photo"))
        self.label_7.setText(_translate("register_form", "Type"))
        self.composer_check.setText(_translate("register_form", "Composer"))
        self.ordinary_check.setText(_translate("register_form", "Ordinary"))
        self.photo_button.setText(_translate("register_form", "Choose"))
        self.label_8.setText(_translate("register_form", "Password length most be more than 8 and contain character and number"))
        self.reg_button.setText(_translate("register_form", "Register"))
        self.back_button.setText(_translate("register_form", "Back"))

