# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_album.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_search_album_form(object):
    def setupUi(self, search_album_form):
        search_album_form.setObjectName("search_album_form")
        search_album_form.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(search_album_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 741, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.calendar_widget = QtWidgets.QCalendarWidget(self.verticalLayoutWidget)
        self.calendar_widget.setObjectName("calendar_widget")
        self.horizontalLayout_2.addWidget(self.calendar_widget)
        self.search_calender_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.search_calender_button.setObjectName("search_calender_button")
        self.horizontalLayout_2.addWidget(self.search_calender_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.composer_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.composer_line.setObjectName("composer_line")
        self.horizontalLayout_4.addWidget(self.composer_line)
        self.composer_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.composer_button.setObjectName("composer_button")
        self.horizontalLayout_4.addWidget(self.composer_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.album_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.album_line.setObjectName("album_line")
        self.horizontalLayout.addWidget(self.album_line)
        self.album_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.album_button.setObjectName("album_button")
        self.horizontalLayout.addWidget(self.album_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tags_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tags_line.setObjectName("tags_line")
        self.horizontalLayout_3.addWidget(self.tags_line)
        self.tag_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tag_button.setObjectName("tag_button")
        self.horizontalLayout_3.addWidget(self.tag_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.result_line = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.result_line.setObjectName("result_line")
        self.horizontalLayout_5.addWidget(self.result_line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.back_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)

        self.retranslateUi(search_album_form)
        QtCore.QMetaObject.connectSlotsByName(search_album_form)

    def retranslateUi(self, search_album_form):
        _translate = QtCore.QCoreApplication.translate
        search_album_form.setWindowTitle(_translate("search_album_form", "Form"))
        self.label_2.setText(_translate("search_album_form", "Published date:"))
        self.search_calender_button.setText(_translate("search_album_form", "Search"))
        self.label_4.setText(_translate("search_album_form", "composer: "))
        self.composer_button.setText(_translate("search_album_form", "Search"))
        self.label.setText(_translate("search_album_form", "Album name:"))
        self.album_button.setText(_translate("search_album_form", "Search"))
        self.label_3.setText(_translate("search_album_form", "Tags:"))
        self.tag_button.setText(_translate("search_album_form", "Search"))
        self.label_5.setText(_translate("search_album_form", "Result: "))
        self.back_button.setText(_translate("search_album_form", "Back"))

