# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_music.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_search_music_form(object):
    def setupUi(self, search_music_form):
        search_music_form.setObjectName("search_music_form")
        search_music_form.resize(810, 598)
        self.verticalLayoutWidget = QtWidgets.QWidget(search_music_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_search_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name_search_line.setObjectName("name_search_line")
        self.horizontalLayout.addWidget(self.name_search_line)
        self.name_search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.name_search_button.setObjectName("name_search_button")
        self.horizontalLayout.addWidget(self.name_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.verticalLayoutWidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_2.addWidget(self.calendarWidget)
        self.calender_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calender_button.setObjectName("calender_button")
        self.horizontalLayout_2.addWidget(self.calender_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.tag_search_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tag_search_line.setObjectName("tag_search_line")
        self.horizontalLayout_4.addWidget(self.tag_search_line)
        self.tag_search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tag_search_button.setObjectName("tag_search_button")
        self.horizontalLayout_4.addWidget(self.tag_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lyrics_search_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lyrics_search_line.setObjectName("lyrics_search_line")
        self.horizontalLayout_5.addWidget(self.lyrics_search_line)
        self.lyrics_search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.lyrics_search_button.setObjectName("lyrics_search_button")
        self.horizontalLayout_5.addWidget(self.lyrics_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.duration_search_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.duration_search_line.setObjectName("duration_search_line")
        self.horizontalLayout_6.addWidget(self.duration_search_line)
        self.duration_search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.duration_search_button.setObjectName("duration_search_button")
        self.horizontalLayout_6.addWidget(self.duration_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.composer_search_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.composer_search_line.setObjectName("composer_search_line")
        self.horizontalLayout_3.addWidget(self.composer_search_line)
        self.composer_search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.composer_search_button.setObjectName("composer_search_button")
        self.horizontalLayout_3.addWidget(self.composer_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.result_line = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.result_line.setObjectName("result_line")
        self.horizontalLayout_7.addWidget(self.result_line)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.back_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)

        self.retranslateUi(search_music_form)
        QtCore.QMetaObject.connectSlotsByName(search_music_form)

    def retranslateUi(self, search_music_form):
        _translate = QtCore.QCoreApplication.translate
        search_music_form.setWindowTitle(_translate("search_music_form", "Form"))
        self.label.setText(_translate("search_music_form", "Name: "))
        self.name_search_button.setText(_translate("search_music_form", "Search"))
        self.label_2.setText(_translate("search_music_form", "Published date:"))
        self.calender_button.setText(_translate("search_music_form", "Search"))
        self.label_4.setText(_translate("search_music_form", "Tags:"))
        self.tag_search_button.setText(_translate("search_music_form", "Search"))
        self.label_5.setText(_translate("search_music_form", "Lyrics:"))
        self.lyrics_search_button.setText(_translate("search_music_form", "Search"))
        self.label_6.setText(_translate("search_music_form", "Duration:"))
        self.duration_search_button.setText(_translate("search_music_form", "Search"))
        self.label_3.setText(_translate("search_music_form", "Composer:"))
        self.composer_search_button.setText(_translate("search_music_form", "Search"))
        self.label_7.setText(_translate("search_music_form", "Result:"))
        self.back_button.setText(_translate("search_music_form", "Back"))

